apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tfs-server
  name: tfs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tfs-server
  strategy: {}
  template:
    metadata:
      labels:
        app: tfs-server
    spec:
      containers:
      - image: gcr.io/fast-ai-exploration/tfserving-hf-vit
        name: tfs-k8s
        imagePullPolicy: Always
        ports:
        - containerPort: 8500
          name: grpc
        - containerPort: 8501
          name: restapi
        resources: {}